name: CI

on:
  push:
  pull_request:

jobs:
  windows-build-test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore
        run: dotnet restore OptiScalerInstaller.slnx

      - name: Build
        run: dotnet build OptiScalerInstaller.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test OptiScalerInstaller.slnx --configuration Release --no-build

      - name: Publish self-contained app payload
        run: dotnet publish .\src\OptiScalerInstaller.App\OptiScalerInstaller.App.csproj --configuration Release /p:PublishProfile=WinX64SelfContained /p:PublishDir=artifacts\ci\publish\
